### PR TITLE
Fixed empty dirs that take OS absolute path

### PR DESCRIPTION
**Pull request by wcapellan**
This is not needed, instead if people want to create empty dirs they should just create a file into dir.

### CODE REVIEW

**Comment by revmischa** [comment]
I'm pretty sure I added that for a reason, although I can't remember what it was right now

**Comment by wcapellan** [comment]
The thing is, when you look for your function to edit it, and save it, you return to the next day and search again to edit it and find this super directory in the temporary directory. It does not contain anything but is the complete tree to the temporary directory previously created. If this directory is not removed, it will be joined with the following ones so that it fails and the function can not be opened by the plugin since the directory is very deep.

**Comment by revmischa** [comment]
When you return the next day to edit it you should re-open the function via the "Edit Function" menu item, not by re-opening the temporary directory.

**Comment by wcapellan** [comment]
That's is exactly what I do. I'm gonna make a video recreating the bug.

**Comment by revmischa** [comment]
Okay, if it works then great

**Comment by wcapellan** [comment]
Thanks @revmischa here is the video that shows the bug fixed with this change. [Watch the video](https://youtu.be/RGEIMOQQFhE)
And thank you for this amazing plugin, I can't work without this.

**Comment by revmischa** [comment]
Ok thanks for the fix! I definitely had that code there for a reason though... I just can't remember it right now.

**Pull request merged**
